  services:

    nats-server:
      image: nats:latest
      ports:
        - "4222:4222"
        - "8222:8222"

    roles-db:
      container_name: roles-database
      image: postgres:17.4
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${ROLES_DB_USERNAME}
        POSTGRES_PASSWORD: ${ROLES_DB_PASSWORD}
        POSTGRES_DB: ${ROLES_DB_NAME}
      volumes:
        - ./roles-ms/postgres:/var/lib/postgresql/data

    staff-db:
      container_name: staff-database
      image: postgres:17.4
      restart: always
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: ${STAFF_DB_USERNAME}
        POSTGRES_PASSWORD: ${STAFF_DB_PASSWORD}
        POSTGRES_DB: ${STAFF_DB_NAME}
      volumes:
        - ./staff-ms/postgres:/var/lib/postgresql/data

    users-db:
      container_name: users-database
      image: postgres:17.4
      restart: always
      ports:
        - "5434:5432"
      environment:
        POSTGRES_USER: ${USERS_DB_USERNAME}
        POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
        POSTGRES_DB: ${USERS_DB_NAME}
      volumes:
        - ./users-ms/postgres:/var/lib/postgresql/data