  services:

    nats-server:
      image: nats:latest
      ports:
        - "4222:4222"
        - "8222:8222"

    roles-db:
      container_name: roles-database
      image: postgres:17.4
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${ROLES_DB_USERNAME}
        POSTGRES_PASSWORD: ${ROLES_DB_PASSWORD}
        POSTGRES_DB: ${ROLES_DB_NAME}
      volumes:
        - ./roles-ms/postgres:/var/lib/postgresql/data